bot:
  name: SomeBankBot
  token: ${BOT_TOKEN}

khasmamedov-middle-service:
  url: http://localhost:8081/v2/api

server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  messages:
    encoding: UTF-8
