# .github/release.yml

name: release-please
on:
  push:
    branches:
      - "f*"
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module # Multiple release types are supported
          default-branch: trunk